-- MySQL Script generated by MySQL Workbench
-- 03/27/17 14:02:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `manager` DEFAULT CHARACTER SET utf8 ;
USE `manager` ;

-- -----------------------------------------------------
-- Table `manager`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager`.`customer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `cnp` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `manager`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` TINYTEXT NULL DEFAULT NULL,
  `password` TINYTEXT NULL DEFAULT NULL,
  `isadmin` TINYINT(1) NULL DEFAULT NULL,
  `firstname` TINYTEXT NULL DEFAULT NULL,
  `lastname` TINYTEXT NULL DEFAULT NULL,
  `address` CHAR(50) NULL DEFAULT NULL,
  `dateofbirth` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `manager`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager`.`orders` (
  `id` INT(11) NOT NULL,
  `idCustomer` INT(11) NULL DEFAULT NULL,
  `idEmployee` INT(11) NULL DEFAULT NULL,
  `shippindAddress` VARCHAR(45) NULL DEFAULT NULL,
  `identificationNr` INT(25) NULL DEFAULT NULL,
  `deliveryDate` DATE NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `idCustomer_idx` (`idCustomer` ASC),
  INDEX `idEmployee_idx` (`idEmployee` ASC),
  CONSTRAINT `idCustomer`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `manager`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idEmployee`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `manager`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `manager`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` TINYTEXT NULL DEFAULT NULL,
  `description` TINYTEXT NULL DEFAULT NULL,
  `color` TINYTEXT NULL DEFAULT NULL,
  `size` DOUBLE NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `stock` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
